

export const icons = [
    'aff_amazons_icon',
    'aff_bane_icon',
    'aff_batman_icon',
    'aff_birds_icon',
    'aff_ccv_icon',
    'aff_crime_icon',
    'aff_joker_icon',
    'aff_league_icon',
    'aff_militia_icon',
    'aff_mrfreeze_icon',
    'aff_owls_icon',
    'aff_penguin_icon',
    'aff_poison_icon',
    'aff_riddler_icon',
    'aff_twoface_icon',
    'aff_unknown_icon',
    'ammo_icon',
    'audacity_0_icon',
    'audacity_1_icon',
    'background_attack',
    'background_defense',
    'background_endurance',
    'background_movement',
    'background_special',
    'background_strength',
    'background_willpower',
    'batclaw_icon',
    'blood_icon',
    'blood',
    'card',
    'clock_black_24dp',
    'crown_icon',
    'eff_blind_icon',
    'eff_cooled_icon',
    'eff_enerv1_icon',
    'eff_enerv2_icon',
    'eff_enerv3_icon',
    'eff_fire_icon',
    'eff_freeze_icon',
    'eff_paralize_icon',
    'eff_poison1_icon',
    'eff_poison2_icon',
    'eff_poison3_icon',
    'eff_poison4_icon',
    'eff_scared_icon',
    'eff_stunned_icon',
    'eff_terror1_icon',
    'eff_terror2_icon',
    'eff_terror3_icon',
    'event_icon',
    'faith_icon',
    'grey_form',
    'injury',
    'interrog_icon',
    'kd_icon',
    'keyboard_black_24dp',
    'ko_icon',
    'less_att_icon',
    'less_def_icon',
    'login_icon',
    'magazine_icon',
    'mov_2_icon',
    'mov_4_icon',
    'mov_6_icon',
    'mov_minus_2_icon',
    'mov_minus_4_icon',
    'mov_minus_6_icon',
    'mtrl_checked_circle',
    'mtrl_chip_checked_black',
    'mtrl_chip_checked_circle',
    'mtrl_chip_close_circle',
    'none_icon',
    'ot_control_icon',
    'ot_menace_icon',
    'ot_protection_icon',
    'ot_violence_icon',
    'phase_i_icon',
    'phase_ii_icon',
    'phase_iii_icon',
    'phase_iv_icon',
    'plus_att_icon',
    'plus_def_icon',
    'rank_freeagent',
    'rank_henchman',
    'rank_leader',
    'rank_legend',
    'rank_sidekick',
    'rank_vehicle',
    'rank_freeagent_icon',
    'rank_henchman_icon',
    'rank_leader_icon',
    'rank_legend_icon',
    'rank_sidekick_icon',
    'rank_vehicle_icon',
    'resource_icon',
    'rof_icon',
    'special_icon',
    'strength_icon',
    'stun',
    'stun_icon',
    'target_icon',
    'tick_icon',
    'wing_icon',
    'wts_instant_icon',
    'wts_round_icon',
    'wts_special_icon',
    'yellow_polygon',
    'yellow_separator',
]


export const ranks = [
    {
        id: 1,
        icon: 'rank_leader'
    },
    {
        id: 2,
        icon: 'rank_sidekick'
    },
    {
        id: 3,
        icon: 'rank_freeagent'
    },
    {
        id: 5,
        icon: 'rank_henchman'
    },
    {
        id: 4,
        icon: 'rank_vehicle'
    },
    {
        id: 6,
        icon: 'rank_legend'
    },
]